export const ErrorCodes = {
  // 400
  MISSING_FIELD: 'MISSING_FIELD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  PASSWORD_TOO_SHORT: 'PASSWORD_TOO_SHORT',
  INVALID_CODE: 'INVALID_CODE',
  CODE_EXPIRED: 'CODE_EXPIRED',
  INVALID_FIELD: 'INVALID_FIELD',
  
  // 401
  NO_TOKEN: 'NO_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  DEVICE_MISMATCH: 'DEVICE_MISMATCH',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  
  // 403
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  ACCESS_DENIED: 'ACCESS_DENIED',
  
  // 404
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  
  // 409
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  
  // 500
  DATABASE_ERROR: 'DATABASE_ERROR',
  EMAIL_ERROR: 'EMAIL_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];